apiVersion: v1
kind: Pod
metadata:
  name: nodehelloworld.example.com
  labels:
    app: helloworld
spec:
  containers:
  - name: k8s-demo
    image: stakkato95/kubernetes-test
    ports:
    - name: nodejs-port
      containerPort: 8080
